dist: trusty
sudo: false
group: beta
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - pip install pyaml
  - conda env create
  - source activate util
  - pip install -e .
  # Make sure we don't try to use pyqt
  - echo backend:agg > matplotlibrc
  # Get the RC of tensorflow for hessians (TODO: use conda)
  - pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc1-cp35-cp35m-linux_x86_64.whl

script:
  - make tests
